twig:
    file_name_pattern: '*.twig'
    globals:
        dev_email: '%env(DEV_EMAIL)%'
        app_name: '%env(APP_NAME)%'
        app_url: '%env(APP_URL)%'
        app_author: '%env(APP_AUTHOR)%'
        app_title: '%env(APP_TITLE)%'
        app_keyword: '%env(APP_KEYWORD)%'
        app_description: '%env(APP_DESCRIPTION)%'
        app_email: '%env(APP_EMAIL)%'

when@test:
    twig:
        strict_variables: true
